/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bachar
 */
public class AddContact extends javax.swing.JFrame {

    /**
     * Creates new form AddContact
     */
    public AddContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPanel = new javax.swing.JPanel();
        lblFName = new javax.swing.JLabel();
        tfFName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        tfLName = new javax.swing.JTextField();
        lblMobile = new javax.swing.JLabel();
        tfMobile = new javax.swing.JTextField();
        lblLandline = new javax.swing.JLabel();
        tfLandline = new javax.swing.JTextField();
        lblEMail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAddress = new javax.swing.JTextArea();
        lblGrp = new javax.swing.JLabel();
        cbGrp1 = new javax.swing.JCheckBox();
        cbGrp2 = new javax.swing.JCheckBox();
        cbGrp3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Contact");
        setBackground(new java.awt.Color(255, 250, 250));
        setResizable(false);

        addPanel.setBackground(new java.awt.Color(255, 250, 250));
        addPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 255), 2), "Contact Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 3, 12), new java.awt.Color(0, 156, 255))); // NOI18N
        addPanel.setForeground(new java.awt.Color(0, 156, 255));
        addPanel.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblFName.setForeground(new java.awt.Color(0, 156, 255));
        lblFName.setText("First Name:");
        addPanel.add(lblFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        tfFName.setBackground(new java.awt.Color(248, 248, 255));
        tfFName.setForeground(new java.awt.Color(51, 51, 51));
        addPanel.add(tfFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, -1));

        lblLName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLName.setForeground(new java.awt.Color(0, 156, 255));
        lblLName.setText("Last Name:");
        addPanel.add(lblLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        tfLName.setBackground(new java.awt.Color(248, 248, 255));
        tfLName.setForeground(new java.awt.Color(51, 51, 51));
        addPanel.add(tfLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, -1));

        lblMobile.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblMobile.setForeground(new java.awt.Color(0, 156, 255));
        lblMobile.setText("Mobile Number:");
        addPanel.add(lblMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        tfMobile.setBackground(new java.awt.Color(248, 248, 255));
        tfMobile.setForeground(new java.awt.Color(51, 51, 51));
        addPanel.add(tfMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, -1));

        lblLandline.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLandline.setForeground(new java.awt.Color(0, 156, 255));
        lblLandline.setText("Landline Number:");
        addPanel.add(lblLandline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        tfLandline.setBackground(new java.awt.Color(248, 248, 255));
        tfLandline.setForeground(new java.awt.Color(51, 51, 51));
        addPanel.add(tfLandline, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 230, -1));

        lblEMail.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblEMail.setForeground(new java.awt.Color(0, 156, 255));
        lblEMail.setText("E-Mail:");
        addPanel.add(lblEMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        tfEmail.setBackground(new java.awt.Color(248, 248, 255));
        tfEmail.setForeground(new java.awt.Color(51, 51, 51));
        addPanel.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 230, -1));

        lblAddress.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(0, 156, 255));
        lblAddress.setText("Address:");
        addPanel.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        tfAddress.setBackground(new java.awt.Color(248, 248, 255));
        tfAddress.setColumns(20);
        tfAddress.setForeground(new java.awt.Color(51, 51, 51));
        tfAddress.setRows(5);
        jScrollPane1.setViewportView(tfAddress);

        addPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        lblGrp.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblGrp.setForeground(new java.awt.Color(0, 156, 255));
        lblGrp.setText("Groups");
        addPanel.add(lblGrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        cbGrp1.setText("jCheckBox1");
        addPanel.add(cbGrp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        cbGrp2.setText("jCheckBox2");
        addPanel.add(cbGrp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        cbGrp3.setText("jCheckBox3");
        addPanel.add(cbGrp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JCheckBox cbGrp1;
    private javax.swing.JCheckBox cbGrp2;
    private javax.swing.JCheckBox cbGrp3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEMail;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGrp;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLandline;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JTextArea tfAddress;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFName;
    private javax.swing.JTextField tfLName;
    private javax.swing.JTextField tfLandline;
    private javax.swing.JTextField tfMobile;
    // End of variables declaration//GEN-END:variables
}
